# Generated by Django 3.1.4 on 2021-01-04 15:43

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtApidata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
                ('api_base', models.CharField(max_length=255)),
                ('output', models.CharField(max_length=255)),
                ('softname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_region', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=4, unique=True)),
                ('longname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_system', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.table', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='SystemExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=255)),
                ('system', models.ManyToManyField(to='app.System')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.region', to_field='name')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.system', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id_config', models.IntegerField(primary_key=True, serialize=False, validators=[app.validators.validate_one_row])),
                ('games_base_dir', models.CharField(default='/home/manuel/git/gameDBFetch/django/dborg', max_length=1024, validators=[app.validators.validate_file_is_dir])),
                ('games_target_base_dir', models.CharField(default='/home/manuel/git/gameDBFetch/django/dborg', max_length=1024, validators=[app.validators.validate_file_is_dir])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.extapidata', to_field='name')),
            ],
        ),
    ]
