# Generated by Django 3.1.4 on 2021-01-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGameFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FilePathField(match='(.chd|.cdi|.gdi|.zip)$', path='/disks/crucial1TBssd/dreamcast_128/redump', recursive=True)),
                ('crc', models.CharField(max_length=16)),
            ],
        ),
    ]
